// config.js - Constantes iniciales de canciones y Spotify OAuth
const SPOTIFY_CLIENT_ID = "9a0069b06ee54e049ad75eaf99e986fd";

const INITIAL_PLAYLIST = [
  { pos: 1, title: "Stay (Don't Go Away) [feat. Raye]", artist: "David Guetta", bpm: 120, key: "La menor", camelot: "8A" },
  { pos: 2, title: "How Deep Is Your Love", artist: "Calvin Harris, Disciples", bpm: 122, key: "Si menor", camelot: "10A" },
  { pos: 3, title: "This Is What You Came For", artist: "Calvin Harris & Rihanna", bpm: 124, key: "La menor", camelot: "8A" },
  { pos: 4, title: "One Kiss", artist: "Calvin Harris, Dua Lipa", bpm: 124, key: "La menor", camelot: "8A" },
  { pos: 5, title: "21 Reasons (feat. Ella Henderson)", artist: "Nathan Dawe", bpm: 124, key: "Fa# mayor", camelot: "2B" },
  { pos: 6, title: "Wake Me Up", artist: "Avicii", bpm: 124, key: "Re mayor", camelot: "10B" },
  { pos: 7, title: "Take Over Control (feat. Eva Simons)", artist: "Afrojack", bpm: 130, key: "Do menor", camelot: "5A" },
  { pos: 8, title: "Titanium (feat. Sia)", artist: "David Guetta", bpm: 126, key: "Do menor", camelot: "5A" },
  { pos: 9, title: "Drinking from the Bottle (feat. Tinie Tempah)", artist: "Calvin Harris", bpm: 128, key: "La menor", camelot: "8A" },
  { pos: 10, title: "Outside (feat. Ellie Goulding)", artist: "Calvin Harris", bpm: 128, key: "Re menor", camelot: "7A" },
  { pos: 11, title: "Summer", artist: "Calvin Harris", bpm: 128, key: "Mi menor", camelot: "9A" },
  { pos: 12, title: "Feel So Close (Radio Edit)", artist: "Calvin Harris", bpm: 128, key: "Sol mayor", camelot: "9B" },
  { pos: 13, title: "Baby Don't Hurt Me", artist: "David Guetta, Anne-Marie & Coi Leray", bpm: 128, key: "Sol mayor", camelot: "9B" },
  { pos: 14, title: "We'll Be Coming Back (feat. Example)", artist: "Calvin Harris", bpm: 128, key: "Sol mayor", camelot: "9B" },
  { pos: 15, title: "Miami 2 Ibiza", artist: "Swedish House Mafia & Tinie Tempah", bpm: 128, key: "Sol mayor", camelot: "9B" },
  { pos: 16, title: "Sweet Nothing (feat. Florence Welch)", artist: "Calvin Harris", bpm: 128, key: "Sol# menor", camelot: "1A" },
  { pos: 17, title: "Who's That Chick? (feat. Rihanna)", artist: "David Guetta", bpm: 128, key: "Si menor", camelot: "10A" },
  { pos: 18, title: "Clarity (feat. Foxes)", artist: "Zedd", bpm: 128, key: "Lab mayor", camelot: "4B" },
  { pos: 19, title: "Head & Heart (feat. MNEK)", artist: "Joel Corry", bpm: 123, key: "Lab mayor", camelot: "4B" },
  { pos: 20, title: "Give Me Everything (feat. Ne-Yo, Afrojack & Nayer)", artist: "Pitbull", bpm: 129, key: "Lab mayor", camelot: "4B" },
  { pos: 21, title: "Don't You Worry Child (feat. John Martin)", artist: "Swedish House Mafia", bpm: 129, key: "Re mayor", camelot: "10B" },
  { pos: 22, title: "Memories (feat. Kid Cudi)", artist: "David Guetta", bpm: 130, key: "Sib menor", camelot: "3A" },
  { pos: 23, title: "Play Hard (feat. Ne-Yo & Akon)", artist: "David Guetta", bpm: 130, key: "Sol# menor", camelot: "1A" },
  { pos: 24, title: "Sexy Bitch (feat. Akon)", artist: "David Guetta", bpm: 130, key: "Si menor", camelot: "10A" },
  { pos: 25, title: "Where Them Girls At (feat. Flo Rida & Nicki Minaj)", artist: "David Guetta", bpm: 130, key: "Mib mayor", camelot: "5B" },
  { pos: 26, title: "Stay the Night (feat. Hayley Williams)", artist: "Zedd", bpm: 128, key: "La mayor", camelot: "11B" },
  { pos: 27, title: "Bad (feat. Vassy)", artist: "David Guetta & Showtek", bpm: 128, key: "Fa menor", camelot: "4A" },
  { pos: 28, title: "Silhouettes", artist: "Avicii", bpm: 128, key: "Fa menor", camelot: "4A" },
  { pos: 29, title: "Levels", artist: "Avicii", bpm: 126, key: "Do# menor", camelot: "12A" },
  { pos: 30, title: "Won't Look Back", artist: "Duke Dumont", bpm: 124, key: "Lab menor", camelot: "1A" },
  { pos: 31, title: "I Got U (feat. Jax Jones)", artist: "Duke Dumont", bpm: 121, key: "La menor", camelot: "8A" },
  { pos: 32, title: "Rather Be (feat. Jess Glynne)", artist: "Clean Bandit", bpm: 121, key: "Si mayor", camelot: "7B" },
  { pos: 33, title: "The Motto", artist: "Tiësto & Ava Max", bpm: 120, key: "Sib menor", camelot: "3A" },
  { pos: 34, title: "Overdrive (feat. Norma Jean Martine)", artist: "Ofenbach", bpm: 127, key: "Reb mayor", camelot: "3B" },
  { pos: 35, title: "Animals", artist: "Martin Garrix", bpm: 128, key: "Reb mayor", camelot: "3B" },
  { pos: 36, title: "Sun Is Shining", artist: "Axwell Λ Ingrosso", bpm: 132, key: "Re mayor", camelot: "10B" },
  { pos: 37, title: "I'm Good (Blue)", artist: "David Guetta & Bebe Rexha", bpm: 128, key: "Sol menor", camelot: "6A" },
  { pos: 38, title: "Where You Are", artist: "John Summit & HAYLA", bpm: 126, key: "La menor", camelot: "8A" }
];

const EDM_CANDIDATES_POOL = [
  { title: "Heroes (We Could Be) [feat. Tove Lo]", artist: "Alesso", bpm: 126, camelot: "10B", isExtended: true, phase: "Ascenso 124->128" },
  { title: "Million Voices", artist: "Otto Knows", bpm: 126, camelot: "5B", isExtended: true, phase: "Pico 126->128" },
  { title: "Reload (Vocal Mix)", artist: "Sebastian Ingrosso, Tommy Trash, John Martin", bpm: 128, camelot: "9B", isExtended: true, phase: "Pico 128 BPM" },
  { title: "Calling (Lose My Mind)", artist: "Sebastian Ingrosso & Alesso", bpm: 126, camelot: "10B", isExtended: true, phase: "Ascenso 124->128" },
  { title: "If I Lose Myself", artist: "OneRepublic vs. Alesso", bpm: 126, camelot: "10B", isExtended: true, phase: "Ascenso 124->128" },
  { title: "Spectrum (feat. Matthew Koma)", artist: "Zedd", bpm: 130, camelot: "4B", isExtended: true, phase: "Pico Máximo 130 BPM" },
  { title: "I Could Be The One", artist: "Avicii vs Nicky Romero", bpm: 128, camelot: "11B", isExtended: true, phase: "Pico 128 BPM" },
  { title: "The Nights", artist: "Avicii", bpm: 126, camelot: "10B", isExtended: true, phase: "Ascenso 124->126" },
  { title: "Red Lights", artist: "Tiësto", bpm: 125, camelot: "9B", isExtended: true, phase: "Subida Intermedia" },
  { title: "Secrets (feat. Vassy)", artist: "Tiësto & KSHMR", bpm: 128, camelot: "4A", isExtended: true, phase: "Pico 128 BPM" },
  { title: "No Money", artist: "Galantis", bpm: 126, camelot: "3B", isExtended: true, phase: "Re-ascenso Final" },
  { title: "In the Name of Love", artist: "Martin Garrix & Bebe Rexha", bpm: 134, camelot: "3B", isExtended: true, phase: "Clímax Final 132+ BPM" },
  { title: "Tremor", artist: "Dimitri Vegas & Like Mike, Martin Garrix", bpm: 128, camelot: "4A", isExtended: true, phase: "Pico Big Room" },
  { title: "Disarm You (feat. Ilsey)", artist: "Kaskade", bpm: 124, camelot: "8A", isExtended: true, phase: "Valle / Descenso" },
  { title: "Spaceman", artist: "Hardwell", bpm: 128, camelot: "2B", isExtended: true, phase: "Pico Big Room 128 BPM" },
  { title: "Blah Blah Blah", artist: "Armin van Buuren", bpm: 138, camelot: "4A", isExtended: true, phase: "Clímax Ultra Fast" },
  { title: "On My Mind", artist: "Don Diablo", bpm: 126, camelot: "10A", isExtended: true, phase: "Future House Ascenso" },
  { title: "Losing It", artist: "Fisher", bpm: 125, camelot: "4A", isExtended: true, phase: "Tech House Groove" },
  { title: "Piece Of Your Heart (feat. GOODBOYS)", artist: "Meduza", bpm: 124, camelot: "10A", isExtended: true, phase: "Subida Melódica" },
  { title: "Greyhound", artist: "Swedish House Mafia", bpm: 126, camelot: "5A", isExtended: true, phase: "Electro Peak" },
  { title: "Strobe", artist: "deadmau5", bpm: 128, camelot: "1A", isExtended: true, phase: "Progressive Anthem" },
  { title: "Rattle", artist: "Bingo Players", bpm: 128, camelot: "10B", isExtended: true, phase: "Dutch House Peak" },
  { title: "The Code", artist: "W&W & Ummet Ozcan", bpm: 128, camelot: "6A", isExtended: true, phase: "Big Room Drop" },
  { title: "Flashlight", artist: "R3HAB & Deorro", bpm: 128, camelot: "4A", isExtended: true, phase: "Bounce Peak" },
  { title: "Gecko (Overdrive)", artist: "Oliver Heldens & Becky Hill", bpm: 125, camelot: "8A", isExtended: true, phase: "Deep House Drive" },
  { title: "Eternity", artist: "Anyma & Chris Avantgarde", bpm: 126, camelot: "2A", isExtended: true, phase: "Melodic Techno Peak" },
  { title: "Shift", artist: "John Summit", bpm: 126, camelot: "8A", isExtended: true, phase: "Tech House Energy" },
  { title: "Dreams", artist: "David Guetta & MORTEN", bpm: 126, camelot: "10A", isExtended: true, phase: "Future Rave Drop" },
  { title: "Carry You", artist: "Martin Garrix & Third Party", bpm: 128, camelot: "10B", isExtended: true, phase: "Progressive Mainstage" },
  { title: "Boneless", artist: "Steve Aoki, Chris Lake & Tujamo", bpm: 128, camelot: "4A", isExtended: true, phase: "Electro Bang" },
  { title: "Toulouse", artist: "Nicky Romero", bpm: 128, camelot: "4A", isExtended: true, phase: "Classic Peak" },
  { title: "Tsunami", artist: "DVBBS & Borgeous", bpm: 128, camelot: "4A", isExtended: true, phase: "Big Room Anthem" },
  { title: "Booyah", artist: "Showtek, We Are Loud! & Sonny Wilson", bpm: 128, camelot: "4A", isExtended: true, phase: "Reggae-Bounce Drop" },
  { title: "Mammoth", artist: "Dimitri Vegas, Like Mike & Moguai", bpm: 128, camelot: "6A", isExtended: true, phase: "Big Room Classic" },
  { title: "Sun & Moon (feat. Richard Bedford)", artist: "Above & Beyond", bpm: 128, camelot: "9A", isExtended: true, phase: "Trance Progressive" },
  { title: "Pyramids (feat. Luciana)", artist: "DVBBS & Dropgun", bpm: 128, camelot: "4A", isExtended: true, phase: "Vocal Drop Peak" },
  { title: "Runaway (U & I)", artist: "Galantis", bpm: 126, camelot: "3B", isExtended: true, phase: "Vocal Dance Peak" }
];
